rails/config/routes.rb
Rails.application.routes.draw do


 
  root 'static_pages#home'
  get    'dashboard'   => 'lessons#dashboard'
  get '/webhook', to: 'webhook#permission'
  post '/webhook', to: 'webhook#receive'
  get '/test', to: 'test#test'

  resources :lessons
  resources :instructions do
    resources :answers, shallow: true
  end

  resources :answers do 
    resources :answer_jumps, shallow: true
  end

  namespace :api do
    resources :lessons
  end


end

rails/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :instruction
	has_one :lesson, through: :instruction
	has_one :jump, class_name: "AnswerJump", dependent: :destroy

	def next_instruction
		self.jump.instruction if self.jump
	end

	def incorrect?
		self.correct == false
	end

end

rails/app/models/answer_jump.rb
class AnswerJump < ActiveRecord::Base
	validates :answer_id, presence: true, uniqueness: true
	validates :instruction_id, presence: true
	belongs_to :instruction
	belongs_to :answer
end

rails/app/models/lesson.rb
class Lesson < ActiveRecord::Base

	has_many :instructions do 
		def last_index
			return (self.count - 1)
		end

		def reorder_indices(start_index = 0)
			i = start_index
			puts self.inspect
			self.each do |inst|
				inst.update_attribute(:display_index, i) # reorders everything
				i += 1
			end
		end
	end

	has_many :answers, through: :instructions


end

rails/app/controllers/answer_jumps_controller.rb
class AnswerJumpsController < ApplicationController

  
  def new
    @answer = Answer.find(params[:answer_id])
    @jump = AnswerJump.new()
  end

  def create
    jump = AnswerJump.create(jump_params)
    @answer = jump.answer
    respond_to do |format|
      format.html { redirect_to edit_answer_path(jump.answer) }
      format.js
    end
  end

  def edit
    @jump = AnswerJump.find(params[:id])
    @answer = @jump.answer
  end

  def update
    @jump = AnswerJump.find(params[:id])
    @jump.update_attributes(jump_params)
    @answer = @jump.answer
    respond_to do |format|
      format.html { redirect_to edit_answer_path(@answer) }
      format.js
    end
  end

  def destroy
  	jump = AnswerJump.find(params[:id]).destroy
    @answer = jump.answer
    respond_to do |format|
      format.html { redirect_to edit_answer_path(@answer) }
      format.js
    end
  end

  

	private


	def jump_params
		params.require(:answer_jump).permit(:answer_id, :instruction_id)
	end

end

rails/app/controllers/answers_controller.rb
class AnswersController < ApplicationController


	def new
		@instruction = Instruction.find(params[:instruction_id])
		@answer = @instruction.answers.build
		respond_to do |format|
			format.html
			format.js
		end
	end

	def create
		@instruction = Instruction.find(params[:instruction_id])
		@answer = @instruction.answers.build(answer_params)
		@answer.save
		respond_to do |format|
			format.html { redirect_to lesson_path(@instruction.lesson) }
			format.js
		end
	end


	def show
		@answer = Answer.find(params[:id])	
		respond_to do |format|
			format.html
			format.js
		end
	end

	def edit
		@answer = Answer.find(params[:id])	
		@instruction = @answer.instruction
		@jump = @answer.jump
		@jump ||= AnswerJump.new()
		respond_to do |format|
			format.html
			format.js
		end
	end


	def update
		@answer = Answer.find(params[:id])	
		@answer.update_attributes(answer_params)
		respond_to do |format|
			format.html { redirect_to lesson_path(@answer.instruction.lesson) }
			format.js
		end
	end


	def destroy
		@answer = Answer.find(params[:id]).destroy
		respond_to do |format|
			format.html { redirect_to lesson_path(@answer.instruction.lesson) }
			format.js
		end
	end



	private

		def answer_params
			params.require(:answer).permit(:text, :image_url, :correct)
		end
end

rails/app/controllers/api/lessons_controller.rb
class Api::LessonsController < ApplicationController
	skip_before_filter :verify_authenticity_token

	def show
		@lesson = Lesson.find(params[:id])	
		@instructions = @lesson.instructions
		@answers = Answer.where( instruction_id: @instructions.pluck(:id) )
		puts @answers.inspect
		@jumps = AnswerJump.where( answer_id: @answers.pluck(:id) )
		response = {}

		response[:lesson] = @lesson
		response[:instructions] = Hash[@instructions.map{|i| [i.id, i ] }]
		response[:answers] = Hash[@answers.map{|a| [a.id, a ] }]
		response[:jumps] = Hash[@jumps.map{|j| [j.id, j ] }]

		render json: response
	end


	def index
		render json: Lesson.all
	end



end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

	
	def dashboard
	end

	def new
		@lesson = Lesson.new
	end

	def create
		@lesson = Lesson.new(lesson_params)
		if @lesson.save
			redirect_to lesson_path(@lesson)
		else
			render 'new'
		end
	end

	def edit
		@lesson = Lesson.find(params[:id])
		@new_instruction = Instruction.new()
		respond_to do |format|
			format.html
			format.js
		end
	end


	def update
		@lesson = Lesson.find(params[:id])
		@lesson.update_attributes(lesson_params)
		redirect_to lesson_path(@lesson)
	end


	def show
		@lesson = Lesson.find(params[:id])
		@new_instruction = Instruction.new()
		respond_to do |format|
			format.html
			format.js
		end
	end

	def index
		@lessons = Lesson.all
	end



	private


	def lesson_params
		params.require(:lesson).permit(:name, :category, :description, :image_url)
	end

end

rails/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	layout 'static_pages'

	def home
	end

end

rails/app/helpers/answer_jumps_helper.rb
module AnswerJumpsHelper
end

rails/app/helpers/answers_helper.rb
module AnswersHelper
end

rails/app/helpers/api/lessons_helper.rb
module Api::LessonsHelper
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/instructions_helper.rb
module InstructionsHelper
end

rails/app/helpers/lessons_helper.rb
module LessonsHelper
end

rails/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

rails/app/views/answer_jumps/_edit.html.erb
<%= form_for @jump, remote: true do |f| %>
    <%= f.hidden_field :answer_id, value: @answer.id  %>
    <% if !@jump.new_record? %>
        <span class="pull-right text-muted small"><em><a href="#instruction_<%= @answer.next_instruction.id %>">Jumps to instruction <%= @answer.next_instruction.id %></a></em></span>
        <% else %>
        <span class="pull-right text-muted small"><em>Goes to next instruction if selected</em></span>
    <% end %>
    </br>
    <div class="form-group">
        <%= f.label :instruction_id, class: "control-label" %>
        <%= f.select(:instruction_id, options_for_select(@answer.instruction.lesson.instructions.map{|i| ["#{i.id}: #{i.text}", i.id] }) , class: "form-control") %>
    </div>                            
    <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-xs btn-success' %>
    </div>
    <span class="text-primary"><%= link_to "cancel", answer_path(@answer), remote: true %></a></em></span>
<% end %>

rails/app/views/answer_jumps/_new.html.erb
<%= form_for @jump, url: answer_answer_jumps_path(@answer), remote: true do |f| %>
    <%= f.hidden_field :answer_id, value: @answer.id  %>
    
    <% if !@jump.new_record? %>
        <span class="pull-right text-muted small"><em><a href="#instruction_<%= @answer.next_instruction.id %>">Jumps to instruction <%= @answer.next_instruction.id %></a></em></span>
        <% else %>
        <span class="pull-right text-muted small"><em>Goes to next instruction if selected</em></span>
    <% end %>
    </br>
    <div class="form-group">
        <%= f.label :instruction_id, class: "control-label" %>
        <%= f.select(:instruction_id, options_for_select(@answer.instruction.lesson.instructions.map{|i| ["#{i.id}: #{i.text}", i.id] }) , class: "form-control") %>
    </div>                            
    <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-xs btn-success' %>
    </div>
    <span class="text-primary"><%= link_to "cancel", answer_path(@answer), remote: true %></a></em></span>
<% end %>

rails/app/views/answer_jumps/create.html.erb
<h1>AnswerJumps#create</h1>
<p>Find me in app/views/answer_jumps/create.html.erb</p>

rails/app/views/answer_jumps/create.js.erb
$("#answer_<%= @answer.id %>").replaceWith("<%= escape_javascript render partial: 'answers/show', locals: {answer: @answer} %>");

rails/app/views/answer_jumps/destroy.html.erb
<h1>AnswerJumps#destroy</h1>
<p>Find me in app/views/answer_jumps/destroy.html.erb</p>

rails/app/views/answer_jumps/destroy.js.erb
$("#answer_<%= @answer.id %>").replaceWith("<%= escape_javascript render partial: 'answers/show', locals: {answer: @answer} %>");

rails/app/views/answer_jumps/edit.js.erb
$("#answer_<%= @answer.id %>_jump").html('<%= escape_javascript render partial: 'edit' %>');

rails/app/views/answer_jumps/new.js.erb
$("#answer_<%= @answer.id %>_jump").html('<%= escape_javascript render partial: 'new' %>');

rails/app/views/answer_jumps/update.html.erb
<h1>AnswerJumps#update</h1>
<p>Find me in app/views/answer_jumps/update.html.erb</p>

rails/app/views/answers/_edit.html.erb
<li id="answer_<%= @answer.id %>" class="timeline-inverted <%= "dependent_instruction_#{@answer.instruction.id}" %>">
    <% if @answer.correct? %>
        <div class="timeline-badge success"><i class="fa fa-check"></i>
        </div>
    <% elsif @answer.incorrect? %>  
        <div class="timeline-badge warning"><i class="fa fa-times"></i>
        </div>
    <% else %>  
        <div class="timeline-badge info"><i class="fa fa-question"></i>
        </div>
    <% end %> 

    <div class="timeline-panel">
        <div class="timeline-heading">
            <h4 class="timeline-title">Edit Answer <%= @answer.id %></h4>
        </div>
        <div class="timeline-body">

            <%= form_for @answer, remote: true do |f| %>
            <%= f.hidden_field :instruction_id, url: instruction_answers_path(@instruction, @answer), value: @instruction.id  %>

            <div class="form-group">
                <%= f.label :text, class: "control-label" %>
                <%= f.text_field :text, class: "form-control"  %>
                <p class="help-block text-muted small">Try to stay below 5 words!</p>
            </div>
            <div class="form-group">
                <%= f.label :image_url, class: "control-label" %>
                <%= f.text_field :image_url, class: "form-control"  %>
                <p class="help-block text-muted small">Or add an image here to stay funky.</p>
            </div>

            <div class="form-group">
                <%= f.label :correct, 'Correct answer', class: "control-label" %>
                <%= f.radio_button(:correct, true) %>
            </div>  
            <div class="form-group">
                <%= f.label :correct, 'Wrong answer', class: "control-label" %>
                <%= f.radio_button(:correct, false) %>
            </div>  
            <p class="help-block text-muted small">This displays a different visual feeback when the answer is chosen.</p>

            <div class="form-group">
                <%= f.submit 'Save', class: 'btn btn-xs btn-success' %>
            </div>
            <% end %>

            <hr>
            <div class="<%= "jump_dependent_answer_to_instruction_#{@answer.next_instruction.id}" if @answer.next_instruction %>">
                <% if !@answer.jump.blank? %>
                <span class="pull-right text-muted small"><em><a href="#instruction_<%= @answer.next_instruction.display_index %>">Jumps to instruction <%= @answer.next_instruction.display_index %></a></em></span>
                <% else %>
                <span class="pull-right text-muted small"><em>Goes to next instruction if selected</em></span>
                <% end %>
                </br>
                <span class="pull-right text-muted small"><em><%= link_to "cancel", answer_path(@answer), remote: true %> / <%= link_to "delete", answer_path(@answer), method: :delete, remote: true %></em></span>
            </div>

        </div>

    </div>

</li>

rails/app/views/answers/_new.html.erb
<div class="new_answer">
<hr>

<span class="pull-right text-muted small"><em><a href="#instruction_<%= @instruction.id %>" onclick="$('#instruction_<%= @instruction.id %> .new_answer').remove();">cancel</a></em></span>

<p class="help-block">Add an answer</p>

<%= form_for @answer, url: instruction_answers_path(@instruction), remote: true do |f| %>
    <div class="form-group">
        <%= f.label :text, class: "control-label" %>
        <%= f.text_field :text, class: "form-control"  %>
        <p class="help-block small">Try to stay below 5 words!</p>
    </div>
    <div class="form-group">
        <%= f.label :image_url, class: "control-label" %>
        <%= f.text_field :image_url, class: "form-control"  %>
        <p class="help-block small">Or add an image here</p>
    </div>

    <div class="form-group">
        <%= f.label :correct, 'Correct answer', class: "control-label" %>
        <%= f.radio_button(:correct, true) %>
    </div>  
    <div class="form-group">
        <%= f.label :correct, 'Wrong answer', class: "control-label" %>
        <%= f.radio_button(:correct, false) %>
    </div>  
    <p class="help-block text-muted small">Displays a positive visual feeback when the correct answer is chosen</p>


    <div class="form-group">
        <%= f.submit 'Add', class: 'btn btn-success' %>
    </div>
<% end %>


</div>

rails/app/views/answers/_show.html.erb
<li id="answer_<%= answer.id %>" class="timeline-inverted <%= "dependent_instruction_#{answer.instruction.id}" %>">
    <% if answer.correct? %>
        <div class="timeline-badge success"><i class="fa fa-check"></i>
        </div>
    <% elsif answer.incorrect? %>  
        <div class="timeline-badge warning"><i class="fa fa-times"></i>
        </div>
    <% else %>  
        <div class="timeline-badge info"><i class="fa fa-question"></i>
        </div>
    <% end %>      


    <div class="timeline-panel">
        <div class="timeline-heading">
            <h4 class="timeline-title"><%= answer.text %></h4>
        </div>
        <div class="timeline-body">

            <div class="row">
                <div class="col-lg-12">
                    <% if false && !answer.text.blank? %>
                        <p><%= answer.text %></p>
                    <% end %>
                    <% if !answer.image_url.blank? %>
                        <img src="<%= answer.image_url %>">
                        </br>
                    <% end %>
                    <span class="pull-right text-muted small"><em><%= link_to "edit", edit_answer_path(answer), remote: true %> / <%= link_to "delete", answer_path(answer), method: :delete, remote: true %></em></span> 
                     </br>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12" id="answer_<%= answer.id %>_jump">
                    <div class="<%= "jump_dependent_answer_to_instruction_#{answer.next_instruction.id}" if answer.next_instruction %>">
                    <% if !answer.jump.blank? %>
                        <span class="pull-right text-muted small"><em><a href="#instruction_<%= answer.next_instruction.id %>">Jumps to instruction <%= answer.next_instruction.display_index %></a> ( <%= link_to "change", edit_answer_jump_path(answer.jump), remote: true %> / <%= link_to "delete", answer_jump_path(answer.jump), method: :delete, remote: true %> )</em></span>
                    <% else %>
                        <span class="pull-right text-muted small"><em>Goes to next instruction if selected (<%= link_to "change", new_answer_answer_jump_path(answer), remote: true %>)</em></span>
                    <% end %>
                </div>
            </div>

        </div>
    </div>

</li>

rails/app/views/instructions/_show.html.erb
<li class="instruction" id="instruction_<%= instruction.id %>">
    <div class="timeline-badge info"><i class="timeline-index fa fa-graduation-cap"></i><span class="timeline-index"><%= instruction.display_index %></span>
    </div>
    <div class="timeline-panel">
        <div class="timeline-heading">
            <h4 class="timeline-title"><%= instruction.text %></h4>
        </div>
        <div class="timeline-body">
            <div class="row">
                <div class="col-lg-12">
                    <% if false && !instruction.text.blank? %>
                        <p><%= instruction.text %></p>
                    <% end %>
                    <% if !instruction.image_url.blank? %>
                        <img src="<%= instruction.image_url %>">
                    <% end %>
                    <% if !instruction.video_url.blank? %>
                        <p>Play video at <%= instruction.video_url %></p>
                    <% end %>
                    <% if !instruction.avatar.blank? %>
                        <img src= "<%=instruction.avatar.url %>" >
                    <% end %>
                    <hr>
                    <span class="pull-right text-muted small"><em><%= link_to "Edit", edit_instruction_path(instruction), remote: true %> / <%= link_to "Add answer", new_instruction_answer_path(instruction), remote: true %> / <%= link_to "Delete", instruction_path(instruction), method: :delete, remote: true, data: {confirm: "Are you sure?"} %></em></span>
                    <br/>
                    <span class="pull-right text-muted small"><em>position: <%= instruction.display_index %> (<%= link_to "move", edit_instruction_path(instruction), remote: true %>)</em></span>
                </div>
            </div>
        </div>
    </div>
</li>

rails/app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to lessons_path, class: 'navbar-brand' do %>
            <%= image_tag('logos/transparent_bg.png', class: 'img-responsive') %></a>
        <% end %>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-messages">
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-messages -->
        </li>

        <!-- /.dropdown -->
        <!-- 
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 1</strong>
                                <span class="pull-right text-muted">40% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    <span class="sr-only">40% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 2</strong>
                                <span class="pull-right text-muted">20% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    <span class="sr-only">20% Complete</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 3</strong>
                                <span class="pull-right text-muted">60% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    <span class="sr-only">60% Complete (warning)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 4</strong>
                                <span class="pull-right text-muted">80% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (danger)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Tasks</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
        </li>
        -->
        <!-- /.dropdown -->
        <!-- 
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small">12 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            
        </li>
        -->
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                
                <li></br></li>
                <li>
                    <%= link_to dashboard_path do %>
                        <i class="fa fa-dashboard fa-fw"></i> Dashboard
                    <% end %>
                </li>
                <li>
                    <%= link_to lessons_path do %>
                        <i class="fa fa-table fa-fw"></i> All Lessons
                    <% end %>
                </li>
                <li>
                    <%= link_to new_lesson_path do %>
                        <i class="fa fa-edit fa-fw"></i> New Lesson
                    <% end %>
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Analytics<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#">Coming</a>
                        </li>
                        <li>
                            <a href="#">Soon</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#"><i class="fa fa-wrench fa-fw"></i> Settings</a>
                </li>
                
                <!--
                <li>
                    <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="panels-wells.html">Panels and Wells</a>
                        </li>
                        <li>
                            <a href="buttons.html">Buttons</a>
                        </li>
                        <li>
                            <a href="notifications.html">Notifications</a>
                        </li>
                        <li>
                            <a href="typography.html">Typography</a>
                        </li>
                        <li>
                            <a href="icons.html"> Icons</a>
                        </li>
                        <li>
                            <a href="grid.html">Grid</a>
                        </li>
                    </ul>
                </li>
                -->

                
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	

	<title>Mako</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

	<script language="javascript">
    	//window.location.href = "<%= lessons_path %>"  <meta http-equiv="refresh" content="0;url=<%= lessons_path %>">
    	</script>

    	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

    <body id="application-body">

    	<div id="wrapper">

    		<%= render partial: 'layouts/nav' %>

    		<div id="page-wrapper">
    			<%= yield %>
    		</div>
    	</div>


    </body>
    </html>